import javax.swing.*;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Mehnaz
 */
public class LiveClass extends javax.swing.JDialog {

    /**
     * Creates new form LiveClass
     */
    public LiveClass(JFrame parent, WorkshopSession session) {
    super(parent, "Live Class", true);
    setSize(400, 300);
    setLocationRelativeTo(parent);

    System.out.println("🟢 Live class opened for: " + session.getTrainer().getName() +
        " | Day " + session.getStartTime().getDay() + " at " + session.getStartTime().getTime());

    JTextArea info = new JTextArea();
    info.setEditable(false);

    StringBuilder details = new StringBuilder();
    details.append("📍 Trainer: ").append(session.getTrainer().getName()).append("\n");
    details.append("🕒 Time: Day ").append(session.getStartTime().getDay())
           .append(" at ").append(session.getStartTime().getTime()).append("\n\n");

    if (session.getParticipants().isEmpty()) {
        details.append("👥 No participants joined yet.");
    } else {
        details.append("👥 Participants:\n");
        for (Participant p : session.getParticipants()) {
            details.append("- ").append(p.getName()).append(" (").append(p.getEmail()).append(")\n");
        }
    }

    info.setText(details.toString());

    JButton leaveBtn = new JButton("Leave");
    leaveBtn.addActionListener(e -> {
        System.out.println("🚪 Live class exited. Returning to Welcome screen.");
        this.dispose();
        new Welcome().setVisible(true);
    });

    setLayout(new BorderLayout());
    add(new JScrollPane(info), BorderLayout.CENTER);
    add(leaveBtn, BorderLayout.SOUTH);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            
            Trainer t1 = new Trainer("Zara", "zara@fit.com", "Yoga");
            Data.addTrainer(t1);

            DateAndTime dt = new DateAndTime(1, "10:00");
            WorkshopSession session = new WorkshopSession(dt, t1);
            session.addParticipant(new Participant("Ali", "ali@gmail.com", "1234567890", "Somewhere", "Male"));
            session.addParticipant(new Participant("Nina", "nina@gmail.com", "88888888", "Nowhere", "Female"));
            Data.addSession(session);

            
            LiveClass dialog = new LiveClass(new JFrame(), session);
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
